type Channel {
    id: ID!
    name: String!
    description: String
    createAt: DateTime
    messages: [Message]!
    private: Boolean!
    workspaceId: ID!
    members: [User]!
    owner: ID!
}

type ChannelMember {
    id: ID!
    channelId: ID!
    userId: ID!
}

type Query {
    getChannel(channelId: ID!): Channel!
    getChannels(workspaceId: ID!): [Channel]!
    getMembersToAddToTheChannel(
        workspaceId: ID!
        channelId: ID!
    ): [ChannelMember]!
}

type Mutation {
    createChannel(
        name: String!
        workspaceId: ID!
        description: String
        private: Boolean = false
    ): Channel!
    addChannelMembers(channelId: ID!, userIds: [ID]!): Boolean
    deleteChannel(id: ID!): Boolean
    addChannelMember(id: ID!, userId: ID!): ChannelMember!
}

# getChannelMembers(channelId: ID!): [User]!
