# const { gql } = require('apollo-server-express');
scalar DateTime
scalar Upload

type Message {
    id: ID!
    text: String!
    user: User!
    channelId: ID!
    createdAt: DateTime!
    url: String
    fileName: String
    fileType: String
}

type Query {
    hi: String!
    getMessages(channelId: ID!): [Message!]!
}

type Mutation {
    createMessage(channelId: ID!, text: String!, file: Upload): Message!
}

type Subscription {
    newMessage(channelId: ID!): Message!
}
