type User {
    id: ID!
    name: String!
    email: String!
    photo: String
    token: String!
    createdAt: DateTime!
    refreshToken: String
}

type Query {
    getUser(userId: ID!): User!
    getUserWorkspaces: [Workspace]!
    # getAllUsers: [User]
}

type Mutation {
    signup(
        name: String!
        email: String!
        password: String!
        confirmPassword: String!
    ): User!

    login(email: String!, password: String!): User!
}
